# Generated by Django 4.2.20 on 2025-12-31 01:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Delivery')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración Delivery',
                'verbose_name_plural': 'Configuraciones Delivery',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(choices=[('mesa 01', 'Mesa 01'), ('mesa 02', 'Mesa 02'), ('mesa 03', 'Mesa 03'), ('mesa 04', 'Mesa 04'), ('mesa 05', 'Mesa 05'), ('mesa 06', 'Mesa 06'), ('mesa 07', 'Mesa 07'), ('mesa 08', 'Mesa 08'), ('mesa 09', 'Mesa 09'), ('mesa 10', 'Mesa 10')], max_length=20, verbose_name='Número de Mesa')),
                ('capacidad', models.IntegerField(default=4, verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plato')),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('principal', 'Plato Principal'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('rapida', 'Comida Rápida'), ('especial', 'Especial del Chef')], max_length=50, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, help_text='Código único del producto', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('postre', 'Postre'), ('carne', 'Carne'), ('verdura', 'Verdura'), ('lacteo', 'Lácteo'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad en stock', max_digits=10, verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=20, unique=True, verbose_name='Código de Pedido')),
                ('tipo_pedido', models.CharField(choices=[('mesa', 'Mesa'), ('delivery', 'Delivery'), ('llevar', 'Para Llevar')], max_length=20, verbose_name='Tipo de Pedido')),
                ('codigo_delivery', models.CharField(blank=True, max_length=10, verbose_name='Código Delivery')),
                ('nombre_cliente', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion_entrega', models.TextField(blank=True, verbose_name='Dirección de Entrega')),
                ('items', models.JSONField(help_text='Lista de platos en formato JSON', verbose_name='Items del Pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparacion', 'En Preparación'), ('listo', 'Listo para Servir'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado del Pedido')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Pedido')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del Pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='facturacion.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Estado Pedido',
                'verbose_name_plural': 'Historial Estados Pedido',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plato', models.IntegerField(verbose_name='ID del Plato')),
                ('nombre_plato', models.CharField(max_length=200, verbose_name='Nombre del Plato')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal Item')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del Item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_items', to='facturacion.pedido')),
            ],
            options={
                'verbose_name': 'Detalle Item Pedido',
                'verbose_name_plural': 'Detalles Items Pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['codigo_pedido'], name='facturacion_codigo__7e8572_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='facturacion_estado_56fa84_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['tipo_pedido'], name='facturacion_tipo_pe_bcdadb_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='facturacion_fecha_p_614a93_idx'),
        ),
    ]
