# Generated by Django 4.2.20 on 2025-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryconfig',
            options={'verbose_name': 'Configuración Código', 'verbose_name_plural': 'Configuraciones Códigos'},
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='tipo',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('llevar', 'Para Llevar')], default='delivery', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='deliveryconfig',
            name='codigo',
            field=models.CharField(choices=[('D001', 'D001'), ('D002', 'D002'), ('D003', 'D003'), ('D004', 'D004'), ('D005', 'D005'), ('L001', 'L001'), ('L002', 'L002'), ('L003', 'L003'), ('L004', 'L004'), ('L005', 'L005')], max_length=10, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryconfig',
            unique_together={('tipo', 'codigo')},
        ),
    ]
