# Generated by Django 4.2.20 on 2025-12-31 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0002_alter_deliveryconfig_options_deliveryconfig_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_factura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Factura')),
                ('tipo_pedido', models.CharField(max_length=20, verbose_name='Tipo de Pedido')),
                ('numero_mesa_codigo', models.CharField(blank=True, max_length=20, verbose_name='Número de Mesa/Código')),
                ('nombre_cliente', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente')),
                ('direccion_entrega', models.TextField(blank=True, verbose_name='Dirección de Entrega')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('anulada', 'Anulada')], default='pagada', max_length=20, verbose_name='Estado de la Factura')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA 12%')),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('items', models.JSONField(help_text='Items en formato JSON', verbose_name='Items de la Factura')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('impresa', models.BooleanField(default=False, verbose_name='Factura Impresa')),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Impresión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facturacion.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_factura'],
            },
        ),
    ]
