# Generated by Django 4.2.20 on 2026-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleitempedido',
            name='tipo_item',
            field=models.CharField(choices=[('plato', 'Plato'), ('bebida', 'Bebida')], default='plato', max_length=20, verbose_name='Tipo de Item'),
        ),
        migrations.AlterField(
            model_name='detalleitempedido',
            name='id_plato',
            field=models.IntegerField(verbose_name='ID del Plato/Bebida'),
        ),
        migrations.AlterField(
            model_name='detalleitempedido',
            name='nombre_plato',
            field=models.CharField(max_length=200, verbose_name='Nombre del Plato/Bebida'),
        ),
    ]
