# Generated by Django 4.2.20 on 2026-01-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_detalleitempedido_tipo_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad retirada')),
                ('motivo', models.CharField(choices=[('venta', 'Venta'), ('dano', 'Daño/Desperdicio'), ('ajuste', 'Ajuste de Inventario'), ('consumo', 'Consumo Interno'), ('otro', 'Otro')], max_length=50, verbose_name='Motivo de salida')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='facturacion.producto')),
            ],
            options={
                'verbose_name': 'Salida de Producto',
                'verbose_name_plural': 'Salidas de Productos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
