# Generated by Django 4.2.20 on 2026-01-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado de la Factura'),
        ),
    ]
