# Generated by Django 4.2.20 on 2026-01-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='factura',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versión'),
        ),
    ]
