# Generated by Django 4.2.20 on 2026-01-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_factura_ultima_actualizacion_factura_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='version',
        ),
    ]
