# Generated by Django 4.2.20 on 2026-01-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_remove_factura_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='facturacion.mesa', verbose_name='Mesa'),
        ),
    ]
