# Generated by Django 4.2.20 on 2026-01-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0013_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AddField(
            model_name='factura',
            name='productos_devueltos',
            field=models.JSONField(blank=True, help_text='Registro de productos devueltos en formato JSON', null=True, verbose_name='Productos Devueltos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('anulada', 'Anulada'), ('parcialmente_devuelta', 'Parcialmente Devuelta'), ('totalmente_devuelta', 'Totalmente Devuelta')], default='pendiente', max_length=30, verbose_name='Estado de la Factura'),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_devolucion', models.CharField(choices=[('total', 'Devolución Total'), ('parcial', 'Devolución Parcial'), ('cambio', 'Cambio de Producto')], max_length=20, verbose_name='Tipo de Devolución')),
                ('productos_devueltos', models.JSONField(help_text='Lista de productos devueltos con cantidades', verbose_name='Productos Devueltos')),
                ('monto_devuelto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Devuelto')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la Devolución')),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='facturacion.factura', verbose_name='Factura')),
                ('procesado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion'],
            },
        ),
    ]
