# Generated by Django 4.2.20 on 2026-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_factura_fecha_devolucion_factura_productos_devueltos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='productos_devueltos',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('anulada', 'Anulada')], default='pendiente', max_length=30, verbose_name='Estado de la Factura'),
        ),
    ]
