# Generated by Django 4.2.20 on 2026-01-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_remove_factura_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AddField(
            model_name='factura',
            name='productos_devueltos',
            field=models.JSONField(blank=True, help_text='Registro de productos devueltos en formato JSON', null=True, verbose_name='Productos Devueltos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('anulada', 'Anulada'), ('parcialmente_devuelta', 'Parcialmente Devuelta'), ('totalmente_devuelta', 'Totalmente Devuelta')], default='pendiente', max_length=30, verbose_name='Estado de la Factura'),
        ),
    ]
