# Generated by Django 4.2.20 on 2026-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_factura_fecha_devolucion_factura_productos_devueltos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de Anulación'),
        ),
    ]
