# Generated by Django 4.2.20 on 2026-02-05 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_factura_descuento_factura_motivo_anulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Debe contener exactamente 11 dígitos', max_length=11, unique=True, verbose_name='Cédula')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono_principal', models.CharField(max_length=10, verbose_name='Teléfono Principal')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Alternativo')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Límite de Crédito')),
                ('dias_credito', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Días de Crédito')),
                ('notas_credito', models.TextField(blank=True, null=True, verbose_name='Notas sobre Crédito')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['cedula'], name='facturacion_cedula_03b75c_idx'), models.Index(fields=['nombre_completo'], name='facturacion_nombre__e3ec1e_idx')],
            },
        ),
    ]
