# Generated by Django 4.2.20 on 2026-03-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=6, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Factura',
                'verbose_name_plural': 'Secuencias de Factura',
            },
        ),
    ]
