# Generated by Django 4.2.20 on 2026-03-28 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_pagocuentacobrar_numero_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentacobrar',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago'),
        ),
    ]
