# Generated by Django 4.2.20 on 2026-03-29 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_alter_pagocuentacobrar_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentacobrar',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de pago'),
        ),
    ]
