# Generated by Django 4.2.20 on 2026-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_alter_pagocuentacobrar_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('trago', 'Trago'), ('postre', 'Postre'), ('carne', 'Carne'), ('verdura', 'Verdura'), ('lacteo', 'Lácteo'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría'),
        ),
    ]
