# Generated by Django 4.2.20 on 2026-03-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0026_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentacobrar',
            name='uuid_pago',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UUID de pago (idempotencia)'),
        ),
    ]
