# Generated by Django 4.2.20 on 2026-03-31 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_pagocuentacobrar_uuid_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentacobrar',
            name='uuid_pago',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID de pago (idempotencia)'),
        ),
    ]
