# Generated by Django 4.2.20 on 2026-04-01 02:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0028_alter_pagocuentacobrar_uuid_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Devuelta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Devuelto')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Pagada'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='monto_devuelto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Devuelto'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='productos_devueltos',
            field=models.JSONField(blank=True, help_text='Campo legacy. Los nuevos registros usan DetalleDevolucion.', null=True, verbose_name='Productos Devueltos (legacy)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada'), ('parcialmente_devuelta', 'Parcialmente Devuelta'), ('totalmente_devuelta', 'Totalmente Devuelta')], default='pendiente', max_length=30, verbose_name='Estado de la Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='productos_devueltos',
            field=models.JSONField(blank=True, help_text='Campo legacy. Los nuevos registros usan DetalleDevolucion.', null=True, verbose_name='Productos Devueltos (legacy)'),
        ),
        migrations.AlterField(
            model_name='pagocuentacobrar',
            name='uuid_pago',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UUID de pago (idempotencia)'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturacion_numero__d0f299_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='facturacion_estado_b4dd64_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_factura'], name='facturacion_fecha_f_053962_idx'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.devolucion', verbose_name='Devolución'),
        ),
    ]
