# Generated by Django 4.2.20 on 2026-04-03 02:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0030_cxc_estado_anulada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('origen', models.CharField(choices=[('VENTA', 'Venta'), ('PAGO_CXC', 'Pago Cuenta por Cobrar'), ('DEVOLUCION', 'Devolución'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste Manual')], max_length=20, verbose_name='Origen')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('REVERTIDO', 'Revertido')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('fecha_operacion', models.DateTimeField(verbose_name='Fecha de Operación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Referencia')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='facturacion.devolucion', verbose_name='Devolución')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='facturacion.factura', verbose_name='Factura')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversos', to='facturacion.movimientofinanciero', verbose_name='Movimiento Original')),
                ('pago_cxc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='facturacion.pagocuentacobrar', verbose_name='Pago CxC')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha_operacion'],
                'indexes': [models.Index(fields=['tipo', 'origen', 'fecha_operacion'], name='facturacion_tipo_7e57f5_idx'), models.Index(fields=['fecha_operacion'], name='facturacion_fecha_o_349b55_idx'), models.Index(fields=['factura'], name='facturacion_factura_4a50ba_idx'), models.Index(fields=['estado'], name='facturacion_estado_20a67d_idx')],
            },
        ),
    ]
