# Generated by Django 4.2.20 on 2026-04-03 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0031_movimientofinanciero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoAFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('devuelto', 'Devuelto'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('uuid_operacion', models.UUIDField(blank=True, help_text='Evita duplicados por reintentos del frontend', null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_favor', to='facturacion.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_generados', to='facturacion.devolucion', verbose_name='Devolución origen')),
                ('factura_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_generados', to='facturacion.factura', verbose_name='Factura origen')),
                ('movimiento_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_liquidados', to='facturacion.movimientofinanciero', verbose_name='Movimiento de liquidación')),
            ],
            options={
                'verbose_name': 'Saldo a Favor',
                'verbose_name_plural': 'Saldos a Favor',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente'], name='facturacion_cliente_8b97bc_idx'), models.Index(fields=['estado'], name='facturacion_estado_fc53e2_idx'), models.Index(fields=['uuid'], name='facturacion_uuid_f57222_idx')],
            },
        ),
    ]
