# Generated by Django 4.2.20 on 2026-04-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0032_saldoafavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('REVERTIDO', 'Revertido')], default='ACTIVO', max_length=10, verbose_name='Estado'),
        ),
    ]
