# Generated by Django 4.2.20 on 2026-04-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0035_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='factura',
            name='factura_tipo_pago_estado_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='facturadetalle',
            name='facturadtalle_factura_producto_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientofinanciero',
            name='movfinanciero_fecha_estado_tipo_origen_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientofinanciero',
            name='movfinanciero_estado_tipo_origen_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_fecha_estado_idx',
        ),
    ]
