# Generated by Django 4.2.20 on 2026-04-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_remove_factura_factura_tipo_pago_estado_fecha_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='Llave de Idempotencia')),
                ('response_data', models.JSONField(verbose_name='Datos de la Respuesta')),
                ('status_code', models.PositiveIntegerField(default=200, verbose_name='Código de Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Fecha de Expiración')),
            ],
            options={
                'verbose_name': 'Llave de Idempotencia',
                'verbose_name_plural': 'Llaves de Idempotencia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='facturacion_key_f2572d_idx'), models.Index(fields=['expires_at'], name='facturacion_expires_398c65_idx')],
            },
        ),
    ]
